# Generated by Django 4.0.2 on 2022-02-15 19:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('topic', models.CharField(max_length=200)),
                ('page_no', models.CharField(choices=[('two', '2'), ('three', '3'), ('four', '4'), ('five', '5'), ('six', '6'), ('seven', '7'), ('eight', '8'), ('nine', '9'), ('ten', '10')], max_length=100, unique=True)),
                ('filename', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['created'],
            },
        ),
        migrations.CreateModel(
            name='Note',
            fields=[
                ('title', models.CharField(max_length=200)),
                ('color', models.CharField(choices=[('#d783ff', 'light purple'), ('#6f42c1', 'purple'), ('#e83e8c', 'pink'), ('#dc6c5f', 'orange'), ('#64b9d2', 'light-blue')], max_length=100)),
                ('intro', models.TextField(blank=True, null=True)),
                ('order', models.IntegerField(blank=True, default=0, null=True)),
                ('filename', models.CharField(blank=True, max_length=200, null=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('belong_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='doc.topic')),
            ],
            options={
                'ordering': ['created'],
            },
        ),
    ]
